<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IncidentOps.Escalation.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IncidentOps.Escalation.Domain\IncidentOps.Escalation.Domain.csproj" />
  </ItemGroup>
</Project>
